---

- name: Add OpenNMS Apt Key
  apt_key:
    url: http://debian.opennms.org/OPENNMS-GPG-KEY
    state: present

- name: Add OpenNMS Apt Repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "{{ opennms_apt[ opennms_apt_source ] }}"
  notify:
    - apt update
