---

- name: Install various RRD tools
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - jrrd
    - rrdtool
    - libxml2-utils
