---

- name: Install OpenNMS
  hosts: opennms
  user: ansible
  sudo: yes

  roles:
    - install_tools
    - setup_opennms_apt
    - maintenance/flush_handlers
    - install_oracle_java
    - install_postgres
    - install_opennms
